title: <p align="center"> Dilip Gehlot </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |

  
  <br>   
  I'm working on Data Science, Spring,Machine learning & NLP related problems.
  Working in Tech domain for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
